version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./webapp:/opt/webapp
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=design
      - POSTGRES_PASSWORD=design
      - POSTGRES_DB=design_db

volumes:
  postgres_data: