version: "3.9"
services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 design_app:app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=design
      - POSTGRES_PASSWORD=design
      - POSTGRES_DB=design_db
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data/

volumes:
  postgres_data:
  redis_data: